[package]
name = "evalback"
version = "0.1.0"
authors = ["Martin Vilcans <martin@resolutiongames.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backroll = { path = "../backroll-rs/backroll" }
bytemuck = "1.5.1"
bevy_tasks = "0.5.0"
minifb = "0.19.3"
